language: java
sudo: false
before_script:
  # Ant build tool configuration
  - cp build.properties.sample build.properties
  - mkdir ./JMetadataQuery/classes
  - sed -i -e "s,jars_dest =,jars_dest =./," build.properties
script:
  # other script steps might be done before running the actual analysis
  - ant jars
  - sonar-scanner
env:
  global:
    - classes=JMetadataQuery/classes
    - jars_dest=./
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: "welle-github" # the key of the org you chose at step #3
